spring:
  application:
    name: microservices

  datasource:
    username: root
    password: Testing@123
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: user
      password: password

server:
  servlet:
    context-path: /microservices/users/api/v1
